### ISSUE TITLE
Uncaught exceptions crashes the application before the Exception is sent to telemetry server

### ISSUE THREAD

**Issue by KrishnaPravin** [microsoft/ApplicationInsights-node.js#513] opened 2019-05-08 12:15 UTC
/out/AutoCollection/Exceptions.js

```
_this._client.trackException({ exception: error }); 
_this._client.flush({ isAppCrashing: true });
if (reThrow) {
    var THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION = error;
    throw THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION; // Error originated somewhere else in your app
}
```

before uncaught exception is sent to the telemetry server the node app gets crashed because of explicitly throwing `THIS_IS_APPLICATION_INSIGHTS_RETHROWING_YOUR_EXCEPTION`

when the throw statement is removed, the exception is properly sent to the telemetry server.

I am using live metrics stream.

**Comment by OsvaldoRosado** [comment] 2019-05-08 15:30
I believe this is expected behavior. This SDK attempts to not change your app’s behavior. An unhandled exception would crash without the SDK, so it will continue to crash with it (the purpose of the rethrow).

Because unhandled exceptions can leave your app in an unsafe state, we don’t send the unhandled exception telemetry out at that time, instead it is synchronously persisted to disk. The next time your app starts up and sends telemetry, it should pick up the information about the crash from disk and send it to Application Insights.

**Comment by markwolff** [comment] 2019-05-14 19:39
Closing this as it is by design

**Closed by markwolff** 2019-05-14 19:39 UTC

**Comment by KrishnaPravin** [comment] 2019-07-01 04:51
> I believe this is expected behavior. This SDK attempts to not change your app’s behavior. An unhandled exception would crash without the SDK, so it will continue to crash with it (the purpose of the rethrow).
> 
> Because unhandled exceptions can leave your app in an unsafe state, we don’t send the unhandled exception telemetry out at that time. Instead, it is synchronously persisted to disk. The next time your app starts up and sends telemetry, it should pick up the information about the crash from disk and send it to Application Insights.

My node.js application is running in a pod which is orchestrated by kubernetes. So 
_when a Container crashes, kubernetes(kubelet) will restart it, but the files will be lost - the Container starts with a clean state._ In this scenario the persisted exception data will be lost.

I faced this in my production application. I did not get the exception logged in App Insights server.

I think it would be better if you crash the application after the unhandled exception telemetry is sent to the Application Insights server.

**Comment by rjkokko** [comment] 2019-08-27 10:31
The problem @KrishnaPravin describes is a very common. You will face it if your application runs in Docker container, any serverless environent including Azure Functions or in any other environment where the host is destroyed after execution.

**Comment by rjkokko** [comment] 2019-08-27 11:33
I ended up catching all exceptions from express.listen(), logging them and flushing buffered messages.
```javascript
{
  app.listen(port, (): Logger => log.info(`${logTag}: Server listening on port ${port}!`));
} catch (e) {
    // log the unhandled exception
    appInsights.defaultClient.trackException({ exception: e });

    appInsights.defaultClient.flush({
      // If isAppCrashing is set true, buffered messages are not sent
      // but saved to the disk. So setting it here false.
      isAppCrashing: false,
      callback: (): void => {
        process.exit();
      },
    });
}
```

**Comment by w0ut0** [comment] 2020-03-31 07:54
@OsvaldoRosado, is it possible to define the location on disk that application insights uses to flush the exception to disks?
We are using docker containers in Azure App Service, and if I can define this location to persistent storage, I would be able to actually receive these exceptions in my AI workspace.
