### ISSUE TITLE
.setAutoCollectDependencies(false) still collects dependencies

### ISSUE THREAD

**Issue by MatejSkrbis** [microsoft/ApplicationInsights-node.js#930] opened 2022-03-29 10:09 UTC
I've updated the application insights package from **1.8.10** to **2.2.2**

Since the update the dependencies are getting collected even when `.setAutoCollectDependencies(false)` is set on setup.
Is there any other option to turn this off in newer version that I missed?

This function worked correctly before the update.

**Comment by hectorhdzg** [comment] 2022-03-29 16:12
Can you describe your environment a little more? is possible your dependencies are coming from different place; can you take a look at SDKVersion field in the unexpected telemetry and share it?

**Comment by MatejSkrbis** [comment] 2022-03-30 06:24
I'm using node 14, windows server 2016.
The dependencies started coming the moment I deployed the code to upgrade insights package from **1.8.10** to **2.2.2**. There were no dependencies in insights before that. There were only exceptions and some custom events which we logged.

SDK field in insights says **node:2.2.2**
The **application_Version** is matching with the latest package version which we automatically increase on commit. So it must be from our latest update.

**Comment by BenjaminBertran** [comment] 2022-04-12 16:03
Hi,
I confirm this behavior if these calls are made on a client:
- setup(key)
- dispose
- again setup(key)

Looking at the code, the variable isEnabled in HttpDependencies is not used [here](
https://github.com/microsoft/ApplicationInsights-node.js/blob/c060888eb97d6a8d55366ebbfc49243f4f2794c4/AutoCollection/HttpDependencies.ts#L79).
... && _this.isEnabled) should be added.
In the meantime, "interceptors" should be removed on http(s).request in dispose() method.

**Comment by Apokalypt** [comment] 2022-04-12 17:32
I agree with Benjamin's comment and I am able to reproduce the problem with the calls he indicated.

The developer's choice about whether or not to track dependencies is not really taken into account since the variable containing this information is only read before initialization. If this variable changes over time, the [trackRequest ](https://github.com/microsoft/ApplicationInsights-node.js/blob/c060888eb97d6a8d55366ebbfc49243f4f2794c4/AutoCollection/HttpDependencies.ts#L140) function seems to continue tracking requests regardless of the developer's choice.

This seems to be part of the problem but the real problem is the way dispose works which does not suppress "interceptors" leading to the possibility of overlapping identical "interceptors" when calling the [setup](https://github.com/microsoft/ApplicationInsights-node.js/blob/c060888eb97d6a8d55366ebbfc49243f4f2794c4/applicationinsights.ts#L106) method after calling the [dispose ](https://github.com/microsoft/ApplicationInsights-node.js/blob/c060888eb97d6a8d55366ebbfc49243f4f2794c4/applicationinsights.ts#L437) method.

**Comment by hectorhdzg** [comment] 2022-04-12 18:58
@MatejSkrbis are you also disposing the telemetry client at some point?, auto collection of dependencies could also be enabled through configuration file, please check if APPLICATIONINSIGHTS_CONFIGURATION_FILE env variable is present or if applicationinsights.json have the setting on, more info [here](https://github.com/microsoft/ApplicationInsights-node.js#configuration). @BenjaminBertran  and @Apokalypt  I will investigate the dispose issue, not sure it is the cause of original issue reported here.

**Comment by Apokalypt** [comment] 2022-04-12 19:07
> auto collection of dependencies could also be enabled through configuration file, please check if APPLICATIONINSIGHTS_CONFIGURATION_FILE env variable is present or if applicationinsights.json have the setting on, more info [here](https://github.com/microsoft/ApplicationInsights-node.js#configuration).

For my part, the file is completely empty ( file content : '{ }' ). All properties are defined with their respective methods ( e.g. : .setAutoCollectDependencies(true) to collect dependencies automatically )
It is perhaps a different problem which is evoked initially but the result being identical (duplicate of collect) I thought that it was interesting to check and to evoke it 👍

**Comment by MatejSkrbis** [comment] 2022-04-13 06:14
> @MatejSkrbis are you also disposing the telemetry client at some point?, auto collection of dependencies could also be enabled through configuration file, please check if APPLICATIONINSIGHTS_CONFIGURATION_FILE env variable is present or if applicationinsights.json have the setting on, more info [here](https://github.com/microsoft/ApplicationInsights-node.js#configuration). @BenjaminBertran and @Apokalypt I will investigate the dispose issue, not sure it is the cause of original issue reported here.

I am not disposing the telemetry client at any point. APPLICATIONINSIGHTS_CONFIGURATION_FILE is not present and I do not have applicationinsights.json settings file.

**Comment by jak-hammond** [comment] 2022-06-20 21:06
Is there any idea when this fix is going to be released, we've recently updated our dependencies and have seen a massive uptick in the amount of information being sent into App Insights instances, two specific event types alone in the Azure Storage SDK have been producing close to 22 million events in a 24 hour period despite us having explicitly turned off the auto-collection of dependencies.

In the meantime, I assume the suggested workaround would be to use the JSON file in the install location of the library?

**Comment by jak-hammond** [comment] 2022-06-21 10:03
Is this still an issue? I can see some code was merged, but after grabbing the latest `2.3.3` version from NPM and running a test with the below config, when I make a connection to a test blob storage account, I am still seeing 2 dependency events being logged in AI.

![image](https://user-images.githubusercontent.com/664193/174773858-10bbe316-eb87-4b04-ab3f-b99f9483c274.png)

**Comment by hectorhdzg** [comment] 2022-06-21 23:26
@MatejSkrbis are the dependencies you were seeing related to Azure SDK calls? if that is the case, I can close this issue with related changes.

**Comment by MatejSkrbis** [comment] 2022-06-22 05:55
@hectorhdzg I do not understand what you are asking me. I just described my issue and downgraded application insights to 1.8.10 and have no intention to update it back until this issue is fixed.

**Closed** 2022-06-22 18:21 UTC
