### ISSUE TITLE
Add Live Metrics Stream Support to the Node.js Version of Application Insights

### ISSUE THREAD

**Issue by bhedge** [Microsoft/ApplicationInsights-node.js#431] opened 2018-10-01 21:14 UTC
It has been requested by quite a few team members to provide support for the Live Metrics Stream into the node.js version of the Application Insights driver to make the metrics available in the portal for viewing. Is this change on the road map and/or technically possible?

**Comment by OsvaldoRosado** [comment] 2018-10-01 21:18
Closing as a duplicate of #92

Please do upvote the uservoice / feedback.azure.com link listed within #92 ! Upvotes there help determine the roadmap and priority for new features.

**Closed by OsvaldoRosado** 2018-10-01 21:18 UTC

**Comment by markwolff** [comment] 2019-04-03 22:15
Updating this thread to mention that live metrics was just added to version `1.3.0` of the SDK
