### ISSUE TITLE
Is there anyway to turn off the new Zone monkey patching?

### ISSUE THREAD

**Issue by eamodio** [Microsoft/ApplicationInsights-node.js#266] opened 2017-06-07 15:59 UTC
Because I have application insights enabled in GitLens (a vscode extension), and the Zone stuff is on by default, the whole extensions process is effected. I don't want to be responsible for causing issues with other extensions because of this and will ultimately have to remove application insights if it can't be localized to just my code.

Related to https://github.com/Microsoft/ApplicationInsights-node.js/issues/267

**Comment by OsvaldoRosado** [comment] 2017-06-07 16:07
You can easily disable Zone by using `.setAutoDependencyCorrelation(false)` before calling `.start()`.

You may also want to disable diagnostic channel, which does patching of its own to collect dependency information from libraries like mongo and redis. To do so you can do something like
```
var diagChannelState = process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'];
process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = true;
var appInsights = require('applicationinsights');
process.env['APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL'] = diagChannelState;
```
(The complication here of saving the current state and restoring is just to keep the original state the same in case other VS code extensions want to turn it on)

**Comment by eamodio** [comment] 2017-06-07 16:12
@OsvaldoRosado thank you for the quick response! Great thank you -- I didn't (don't) see `setAutoDependencyCorrelation` isn't in the type definition.

I do already have the diag channel patch in there :)

**Comment by OsvaldoRosado** [comment] 2017-06-07 16:17
Are you using the latest version (0.20/0.20.1)? If so up-to-date type definitions should be included directly inside the npm package. Could be a bug in the included tsd if you're not seeing this function on the appInsights object.

**Comment by eamodio** [comment] 2017-06-07 16:24
Hrm, I was using the @types package. I'll remove that (and my own custom typings) and see. Thanks!

**Comment by eamodio** [comment] 2017-06-07 16:30
Do you have an example anywhere that uses it with the types in Typescript? I can't seem to get it to resolve the types properly.

**Comment by OsvaldoRosado** [comment] 2017-06-07 16:41
I believe it's a built in feature of typescript 2.0+ (some info about it at https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html )

There should really be anything you need to do to get it to work. Have application insights npm install-ed and then VSCode should immediately have types for the library.

**Comment by eamodio** [comment] 2017-06-07 17:01
It must be the way I have it setup, see [here](https://github.com/eamodio/vscode-gitlens/blob/master/src/telemetry.ts#L34), if I remove my custom typings, then I get errors that `ApplicationInsights` isn't found

**Comment by OsvaldoRosado** [comment] 2017-06-07 17:05
In the new typing format we aren't directly exporting the class "ApplicationInsights" but rather an object that is an instance of that class. We're still trying to figure out the best way to format the types so that may change.

With the current version, this formatting will work instead:
```
import appInsights = require("applicationInsights");

class Test {
    private ai: typeof appInsights;
}
```

**Comment by eamodio** [comment] 2017-06-07 17:32
Ah got it -- thanks!

**Comment by OsvaldoRosado** [comment] 2017-06-07 20:55
Thanks for the feedback!

Closing this as it looks like the issue is resolved. Please feel free to re-open if you need to!

**Closed by OsvaldoRosado** 2017-06-07 20:55 UTC
