### ISSUE TITLE
Error in Node 10.13.0 - More tasks executed then were scheduled 

### ISSUE THREAD

**Issue by ahce** [Microsoft/ApplicationInsights-node.js#460] opened 2018-11-25 16:49 UTC
**This error doesn't happen in node 8.**

```

C:\[Your_Path]\node_modules\applicationinsights\out\AutoCollection\Exceptions.js:33
                        throw error;
                        ^
Error: More tasks executed then were scheduled.
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (C:\[Your_Path]\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:182:18)
    at ZoneDelegate._updateTaskCount (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:310:23)
    at ZoneDelegate.cancelTask (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:297:22)
    at Zone.cancelTask (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:174:44)
    at zoneAwareRemoveListener (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1153:28)
    at C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1266:9
    at process.removeListener (eval at createNamedFn (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1207:17), <anonymous>:3:41)
    at process.on (domain.js:151:13)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at _addListener (events.js:211:14)
    at process.prependListener [as __zone_symbol__prependListener] (events.js:266:14)
    at Object.invokeAddFunc (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1065:48)
    at ZoneTask.scheduleEventListener [as scheduleFn] (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1092:21)
    at ZoneDelegate.scheduleTask (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:255:26)
    at Zone.scheduleEventTask (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:171:39)
    at zoneAwareAddListener (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1137:14)
    at C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1266:9
    at process.prependListener (eval at createNamedFn (C:\[Your_Path]\node_modules\zone.js\dist\zone-node.js:1207:17), <anonymous>:3:42)
    at process.on (domain.js:152:13)
    at process.emit (events.js:187:15)
```

## Environment:
- OS: Windows 10 Pro 1809
- Node: 10.13.0
- Applicationinsights: 1.0.7

## Steps to Reproduce
- clone https://github.com/ahce/applicationinsightsBug
- npm install
- npm start or npm run start:watch

**Comment by OsvaldoRosado** [comment] 2018-11-26 19:20
Can you provide code that reproduces this error? There isn't enough information from the stack trace to see the root cause.

Does this exception still throw if you disable automatic dependency correlation?

**Comment by ahce** [comment] 2018-11-26 22:11
@OsvaldoRosado I added steps to reproduce

**Comment by OsvaldoRosado** [comment] 2018-11-26 22:31
Thanks! Don't have a fix to share yet, but it looks like an incompatibility between `restify` and `zone.js` (at least the version of `zone.js` we currently use). You can avoid the error in the meantime by using `setAutoDependencyCorrelation(false)`

**Comment by markwolff** [comment] 2019-01-14 18:58
Updating this thread since we deprecated `zone.js` in #474
@ahce, I believe this is fixed in our current beta version. I tried it in your repro repo and it worked correctly. Try it out and let me know how it goes.
```
npm i applicationinsights@beta
```
or
```
npm i applicationinsights@1.1.0-beta.0
```

**Comment by ahce** [comment] 2019-01-15 00:33
@markwolff Thanks! fixed in v1.1.0-beta.0

**Comment by markwolff** [comment] 2019-01-30 01:17
closing this as 1.1.0 is now released as stable. Thanks for helping to test it out @ahce

**Closed by markwolff** 2019-01-30 01:17 UTC
Labels: bug

**Comment by faridhajnal** [comment] 2019-02-05 20:07
Had the same issue when incorporating winston to my solution. @OsvaldoRosado 's approach did the trick.
Many thanks!

**Comment by markwolff** [comment] 2019-02-06 18:05
Thanks for confirming @faridhajnal. You can also update to the latest version (`1.1.0`) where this is fixed so that you do not need to disable dependency correlation
