### ISSUE TITLE
[Winston] Metadata passed through child logger isn't showing in Application Insights customDimensions

### ISSUE THREAD

**Issue by sawyerh** [microsoft/ApplicationInsights-node.js#515] opened 2019-05-09 22:39 UTC
Environment:

- `winston` - Version `3.2.1`
- `applicationinsights` - Version `1.3.1`
- Node `10.15.3`

Our application is using [Winston's "child loggers" feature](https://github.com/winstonjs/winston/tree/8423c03c59c31f61f57519b4097420a464c90f83#creating-child-loggers) to set metadata defaults on each trace. Below is an example:

```js
// Setup Application Insights
const appInsights = require("applicationinsights");
appInsights
        .setup(process.env.APPINSIGHTS_INSTRUMENTATIONKEY)
        .setAutoDependencyCorrelation(false)
        .start();

...

// Setup Winston
const winston = require("winston");
const logger = winston.createLogger({
      format: winston.format.json()
})

logger.add(new winston.transports.Console())

...

// Create a child logger so subsequent logs include the DB record IDs
const childLogger = logger.child({
    caseIndexingInfoId: caseIndexingInfo.id,
    fileUploadId: fileUpload.id
})

...

// Call the child logger and pass additional metadata
childLogger.info("Processing upload", { storagePath, contentType })
```

## Expected result

Given the above, I would expect to see a `trace` recorded in Application insights with the following as the `customDimensions` shape:

```js
{
  "caseIndexingInfoId": "123",
  "fileUploadId": "456",
  "storagePath": "bar.jpeg",
  "contentType": "image/jpeg",
}
```

## Actual result

- The expected data is getting logged to my console
- _However_, **the trace in Application Insights is not showing the metadata defined on the child logger**.

What I see in my console:

```js
{
  "caseIndexingInfoId": "123",
  "fileUploadId": "456",
  "storagePath": "bar.jpeg",
  "contentType": "image/jpeg",
  "level": "info",
  "message": "Processing upload"
}
```

But this is what I see in Application Insights (notice that `caseIndexingInfoId` and `fileUploadId` are missing from `customDimensions`:

![image](https://user-images.githubusercontent.com/371943/57491153-b5576380-7289-11e9-8503-9b8c654642c9.png)

**Comment by markwolff** [comment] 2019-05-10 00:42
This is happening because winston's `logger.child` implementation is not doing all of the SPLAT stuff that the default logger does for metadata. This seems like an inconsistency on winston's part, but since it is not a bug, I doubt it will be fixed. I will rework how I grab the metadata in the next update. For now you can replace our winston logger patch with this Transport and disable winston patching via the environment variable.

```js
// App Insights setup
const appInsights = require('applicationinsights');
appInsights.setup('')
.setInternalLogging(true,true)
.start();
appInsights.defaultClient.config.maxBatchSize = 1;

// Require in Winston 3.x
var winston = require('winston');
var {createLogger, transports, loggers} = winston;

// App Insights custom Transport
class AppInsightsTransport extends winston.Transport {
  constructor(winston, client, opts) {
    super(opts);
    this.winston = winston;
    this.client = client;
  }

  mapLevelToKind(winston, level) {
    let levelKind;
    if (winston.config.npm.levels[level] != null) {
      levelKind = "npm";
    } else if (winston.config.syslog.levels[level] != null) {
      levelKind = "syslog";
    } else {
      levelKind = "unknown";
    }
    return levelKind;
  };

  log(info, callback) {
    const {message, level} = info;
    const levelKind = this.mapLevelToKind(this.winston, level);
    const meta = {};

    if (typeof Symbol["for"] === "function") {
      const metaSearch = info.meta ? [info.meta] : undefined || info[Symbol["for"]("splat")];
      if (metaSearch) {
        for (const key in metaSearch[0]) {
          if (meta.hasOwnProperty) {
            meta[key] = metaSearch[0][key];
          }
        }
      }
    }

    for (const key in splat) {
    }

    this.client.trackTrace({message: `${level}: ${message}`, properties: meta});
    callback();
  }
}

// Create the loggers
const myLogger = createLogger({
  level: 'info'
});
loggers.add('MY', myLogger);
loggers.options.transports = [new AppInsightsTransport(winston, appInsights.defaultClient)];

const logger = loggers.get('MY');
logger.info('hello world');
```

**Comment by sawyerh** [comment] 2019-05-13 15:54
> This is happening because winston's logger.child implementation is not doing all of the SPLAT stuff that the default logger does for metadata. This seems like an inconsistency on winston's part, but since it is not a bug, I doubt it will be fixed.

If you have the info handy, can you share more details about this, or a reference to where this is in their codebase? I'm open to creating a pull request on the Winston side if it's feasible. I just might need a little more details about what you're describing here.

**Comment by sawyerh** [comment] 2019-05-13 15:54
> This is happening because winston's logger.child implementation is not doing all of the SPLAT stuff that the default logger does for metadata. This seems like an inconsistency on winston's part, but since it is not a bug, I doubt it will be fixed.

@markwolff If you have the info handy, can you share more details about this, or a reference to where this is in their codebase? I'm open to creating a pull request on the Winston side if it's feasible. I just might need a little more details about what you're describing here.

**Comment by markwolff** [comment] 2019-05-13 16:07
@sawyerh For a typical logging situation, there is more complexity in how it handles the metadata field, as per:
https://github.com/winstonjs/winston/blob/8423c03c59c31f61f57519b4097420a464c90f83/lib/winston/logger.js#L227-L257

Compare this to the child logging process, where it simply copies the object over, but misses out on all of the splat stuff.
https://github.com/winstonjs/winston/blob/8423c03c59c31f61f57519b4097420a464c90f83/lib/winston/logger.js#L45-L55

**Comment by markwolff** [comment] 2019-05-13 23:29
Updating this thread to mention that I fixed this on our end [here](https://github.com/microsoft/node-diagnostic-channel/pull/58). This PR on winston's end might also fix it: https://github.com/winstonjs/winston/pull/1598

**Comment by Maverick1872** [comment] 2019-05-14 19:11
> 
> 
> Updating this thread to mention that I fixed this on our end [here](https://github.com/microsoft/node-diagnostic-channel/pull/58). It will land in 1.4.0 in a week or so. This PR on winston's end might also fix it: [winstonjs/winston#1598](https://github.com/winstonjs/winston/pull/1598)

@markwolff, glad to see I'm not the only one who ran into this issue. I'm hoping to get my PR on Winston cleaned up and ready for re-approval this weekend if life allows. That being said I'm not super familiar with the SPLAT functionality and if you want to help verify that's working on the child/root once I get my PR up it would be greatly appreciated!

**Comment by markwolff** [comment] 2019-05-23 19:17
Closing this as the fix is already released. You can just reinstall this SDK to pick up the latest version of `diagnostic-channel-publishers`

**Closed by markwolff** 2019-05-23 19:17 UTC

**Comment by sawyerh** [comment] 2019-05-26 13:32
@markwolff Unfortunately, `diagnostic-channel-publishers` is locked to `0.3.0` in the latest release of `applicationinsights`, so reinstalling the SDK doesn't bump it to `0.3.2`, and adding `diagnostic-channel-publishers@0.3.2` as project dependency doesn't seem to do the trick either: https://github.com/microsoft/ApplicationInsights-node.js/commit/5a3c406c7061f48f9f7977cc0057ed3bbba59ae4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by sawyerh** [comment] 2019-05-31 14:36
@markwolff Sorry to pester you – any idea when `1.4.0` is landing? The issue mentioned in my previous comment is preventing me from inheriting the bug fix applied in `diagnostic-channel-publishers`

**Comment by markwolff** [comment] 2019-05-31 16:46
Hey sorry for the delays. I'm aiming for Monday.
