### ISSUE TITLE
EnvelopeFactory: regression in 0.22.0?

### ISSUE THREAD

**Issue by jeffwilcox** [Microsoft/ApplicationInsights-node.js#322] opened 2017-09-12 17:47 UTC
Is there any chance that the telemetry processor changes in 0.22.0 have caused some issues?

We're using Node 8.4.x and know there have been some changes related to zone error wrapping and management.

Our service is no longer sending interesting errors back, instead we're getting actual errors being generated inside the app insights module. Interestingly, debugging inside VS Code I can actually see the stack on the error, but the propery ["stack"] fails and ends up giving us this information returned to the client.

Any chance you've seen anything like this? I think we're going to roll back to 0.21.0 for now...

```
TypeError: Cannot read property 'stack' of undefined
    at Function.EnvelopeFactory.createExceptionData (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\applicationinsights\out\Library\EnvelopeFactory.js:128:40)
    at Function.EnvelopeFactory.createEnvelope (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\applicationinsights\out\Library\EnvelopeFactory.js:33:40)
    at NodeClient.TelemetryClient.track (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\applicationinsights\out\Library\TelemetryClient.js:97:44)
    at NodeClient.TelemetryClient.trackException (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\applicationinsights\out\Library\TelemetryClient.js:55:14)
    at NodeClient.addProperties (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\lib\insights.js:66:12)
    at module.exports (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\middleware\errorHandler.js:78:22)
    at Layer.handle_error (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:275:10)
    at Layer.handle_error (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\layer.js:67:12)
    at trim_prefix (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\jwilcox\Code\z\win\prod\opensource-repos\node_modules\express\lib\router\index.js:335:12)

```

Sorry if you'd prefer a direct mail or StackOverflow or something vs a post as an issue...

**Comment by OsvaldoRosado** [comment] 2017-09-12 17:50
Thanks for reporting this! We haven't seen this yet.

Are you able to share some sample code that reproduces this?

**Comment by jeffwilcox** [comment] 2017-09-13 14:43
@OsvaldoRosado I'll see what I can come up with. Unfortunately I wasn't able to create a simple reproduction when I first tried, but for us it was a 100% loss of telemetry once the update was deployed, so there's something _somewhere_ impacting! Could be a bug on our end, too. Will be in touch.

**Comment by mparq** [comment] 2017-09-20 22:26
I am seeing the same issue. To reproduce:

```
const appInsights = require('applicationinsights');
appInsights.setup().start();
appInsights.defaultClient.trackException(new Error(`error.exception is undefined, so error.exception['stack'] throws an error within application insights.`));
```

**Comment by OsvaldoRosado** [comment] 2017-09-20 22:30
Ah, this makes sense.

In this example `trackException`'s API is not being followed. Please refer to the new parameters as of version 0.22. `trackException` now takes an object `ExceptionTelemetry`. These replace the previous positional arguments.

https://github.com/Microsoft/ApplicationInsights-node.js/blob/4ff351441ca42cbe151c43a9fc1b6becb3db2e38/Library/TelemetryClient.ts#L72

https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/TelemetryTypes/ExceptionTelemetry.ts

**Comment by mparq** [comment] 2017-09-20 22:36
Ah... oops! Thanks for the quick response.

**Comment by OsvaldoRosado** [comment] 2017-09-22 23:09
@jeffwilcox Does this explanation handle your instance of this error as well?

**Comment by OsvaldoRosado** [comment] 2017-10-17 21:51
Closing for now with the assumption that this is due to incorrect API usage after the breaking API changes in 0.22. Feel free to re-open if this is not from using the old API syntax with the new version!

**Closed by OsvaldoRosado** 2017-10-17 21:51 UTC
Labels: bug

**Comment by jeffwilcox** [comment] 2017-11-21 02:10
@OsvaldoRosado thanks, sorry I missed the closing. Glad now that the project has shipped SemVer can be followed!
