### ISSUE TITLE
Telemetry data stop daily even with small request and reduced sampling

### ISSUE THREAD

**Issue by mehmetilker** [Microsoft/ApplicationInsights-node.js#289] opened 2017-07-19 11:01 UTC
I am using Asp.Net App insights as well and there is no problem with it even with %100 sampling but one of my services (Node.js) is using this library but even thought I reduced sampling to %10 still dail cap finish too early. I am not sanding any extra request. And I cancelled collect request with the following settings.

Is there any other setting I need to do or is it possible node.js library is  storing extra information ?

`
appInsights.setup('xxxx')

		.setAutoDependencyCorrelation(true)
		.setAutoCollectRequests(false)
		.setAutoCollectPerformance(true)
		.setAutoCollectExceptions(true)
		.setAutoCollectDependencies(true)
		.start();
`

**Comment by OsvaldoRosado** [comment] 2017-07-20 01:21
This SDK sends more performance counters than the one for .NET. If you don't use this data, you can try turning off the performance autocollector. Does this app simply generate more events? Take a look in analytics in the various tables there to see the data you're sending to Application Insights. That way you can see the difference between what is being collected

**Comment by mehmetilker** [comment] 2017-07-22 07:54
Performance counter is on in .Net Sdk as well. I assume both .Net and Node Sdk should be identical.
Another thing is that  I see a warning saying that "You have reached your daily data limit. Increase your daily cap to fix this." on Overview tab but does not show and data.

I will try with turning off performance auto collector.

**Comment by OsvaldoRosado** [comment] 2017-07-24 15:45
> Performance counter is on in .Net Sdk as well. I assume both .Net and Node Sdk should be identical.

Ideally this would be the case, but it's not today. The Node SDK sends a different and larger set of counters than .NET. It may also send them at a higher rate, but I haven't looked into that yet. If it does, that's probably causing this issue.

**Comment by mehmetilker** [comment] 2017-07-25 09:36
I have turned performance collector off and still getting warning for daily cap.
On Azure App insight it shows 73 daily request and it seems it is enough to finish the daily cap. 

Is it possible that my config is wrong ?

I put the app insights related code just before app.listen section.
And doing nothing else.
I set sampling to %1 on azure as well.

`
var appInsights = require("applicationinsights");

	appInsights.setup('vvvvvvv')
		.setAutoDependencyCorrelation(true)
		.setAutoCollectRequests(false)
		.setAutoCollectPerformance(false)
		.setAutoCollectExceptions(true)
		.setAutoCollectDependencies(true)
		.start();
}
var server = app.listen(app.get('port'), function() {
`

**Comment by gclifford** [comment] 2017-07-25 22:18
I would also chime in. I am also getting the same issue with my NodeJS project. From what I can tell it is dependency tracking that is eating up most of daily allowance (By daily no where even close to a day).

In version 0.16.0 I never had this issue with the dependencies. This version still had issue were the performance counters would blow by the daily cap in no time.

**Comment by AlexBulankou** [comment] 2017-08-16 23:33
@OsvaldoRosado, what is the bug here? Looks like the problem is the volume of collected dependencies causes daily cap to be reached. This can be mitigated by either:
1. Stopping dependency auto-collection
2. Using telemetry processor to filter out dependencies of specific type
3. Using telemetry processor to set custom sampling for dependencies of specific type. Not sure if this one is supported.

**Comment by OsvaldoRosado** [comment] 2017-08-16 23:35
The bug here is OOB collection of performance counters is too heavy. Some combination of collecting too many counters and reporting too often is the suspicion.

**Comment by OsvaldoRosado** [comment] 2017-09-07 17:51
Closing as code to fix this is now merged in for v0.22. Please re-open if you experience this again on newer releases!

**Closed** 2017-09-07 17:51 UTC
Labels: bug
