### ISSUE TITLE
Windows Defender detecting malware for diagnostic channel dependency

### ISSUE THREAD

**Issue by noobling** [Microsoft/ApplicationInsights-node.js#497] opened 2019-03-21 07:17 UTC
Hello, recently windows defender updated their threat definitions and now detects `Sender.js` in the diagnostic channel dependency as a trojan.

![image](https://user-images.githubusercontent.com/23206864/54737718-37150400-4bec-11e9-9c35-22a5d8fff59f.png)

**Comment by stefanmaretic** [comment] 2019-03-21 07:43
I'm also having this issue.

**Comment by emilpalsson** [comment] 2019-03-21 07:43
We're also having this issue.

**Comment by fezproof** [comment] 2019-03-21 07:52
Do people think its a false positive or an actual Trojan?
I have submitted the file for review to the Microsoft security system and so far it doesn't think its a virus, but it hasn't been reviewed by an analyst yet.

**Comment by pr0gramar** [comment] 2019-03-21 07:55
We are hitting this across our production websites as well.

**Comment by stefanmaretic** [comment] 2019-03-21 07:56
> We're also having this issue. I solve for now by downgrading to 1.0.8 (which goes unreported).
> 
> To make this issue easier to search for: Trojan:Win32/Skeeyah.I

I will try this out in the meantime.

**Comment by fezproof** [comment] 2019-03-21 08:05
Version 1.1.0 seems to work fine as well

**Comment by fezproof** [comment] 2019-03-21 08:15
![image](https://user-images.githubusercontent.com/26830309/54739872-84956f00-4bf4-11e9-90e3-a1906c2d5115.png)

Windows Defender should have an update soon to fix the issue!

**Comment by noobling** [comment] 2019-03-21 08:37
Make sure you clear your yarn cache too 
1. Find your cache directory `yarn cache dir`
2. Cd to your yarn cache directory
3. Delete the cache folder

**Comment by markwolff** [comment] 2019-03-21 16:56
`Sender.ts` was last updated in 1.1.0, but it was a small change that I don't think would trigger this (adding `.unref()` to a timer). Nothing changed for 1.2.0. 
https://github.com/Microsoft/ApplicationInsights-node.js/commits/develop/Library/Sender.ts
Assuming this was caused by Windows Defender definition going too far, which they have since reverted.

Closing this as it seemed to have resolved itself in the meantime, but I will investigate internally.

**Closed by markwolff** 2019-03-21 16:56 UTC
