### ISSUE TITLE
AppInsightsAsyncCorrelatedErrorWrapper Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by rayvaz** [Microsoft/ApplicationInsights-node.js#380] opened 2018-03-22 14:04 UTC
I am using "applicationinsights": "1.0.2" version, 
After starting the process, AppInsights library throwing the error after a while.

<img width="1371" alt="screen shot 2018-03-22 at 16 51 50" src="https://user-images.githubusercontent.com/727137/37774996-bf910b30-2df2-11e8-9d73-bc4f0028f101.png">

**Comment by OsvaldoRosado** [comment] 2018-03-22 14:09
Closing as a duplicate of #377. Please feel free to add comments there if what's already said doesn't cover your issue!

**Closed by OsvaldoRosado** 2018-03-22 14:09 UTC
