### ISSUE TITLE
error event.operationId is not a function

### ISSUE THREAD

**Issue by Spandana-Gajangi** [Microsoft/ApplicationInsights-node.js#423] opened 2018-09-05 11:41 UTC
appInsights.setup(instrumentationKey)
  .setAutoDependencyCorrelation(true)
  .setAutoCollectRequests(true)
  .setAutoCollectPerformance(true)
  .setAutoCollectExceptions(true)
  .setAutoCollectDependencies(true)
  .setAutoCollectConsole(true)
  .setUseDiskRetryCaching(true)
  .start();
const client = appInsights.defaultClient;
client.trackEvent({ name: 'my custom event', properties: { customProperty: 'custom property value' } });
client.trackException({ exception: new Error('handled exceptions can be logged with this method') });
client.trackMetric({ name: 'custom metric', value: 3 });
client.trackTrace({ message: 'trace message' });
client.trackDependency({ target: 'http://dbname', name: 'select customers proc', data: 'SELECT * FROM User', duration: 231, resultCode: 0, success: true, dependencyTypeName: 'ZSQL' });
client.trackRequest({ name: 'GET /customer', url: 'https://myserver/customer', duration: 309, resultCode: 200, success: true });
above code snippet throwing error  event.operationId is not a function

**Comment by OsvaldoRosado** [comment] 2018-09-05 17:14
Which version of the `applicationinsights` package are you using? I can't reproduce this error on the latest (1.0.4).

**Comment by Spandana-Gajangi** [comment] 2018-09-06 07:56
applicationinsights version is 1.0.4

**Comment by OsvaldoRosado** [comment] 2018-09-06 18:28
Can you share the entire script you are running? I've been assuming the only thing missing is the require line to include `applicationinsights` but it would be great to verify this.


Can you also share what version of node you have and any other modules in your package.json?

**Comment by OsvaldoRosado** [comment] 2018-11-01 17:30
Closing for now. Feel free to reopen if you're still having this issue!

**Closed by OsvaldoRosado** 2018-11-01 17:30 UTC
Labels: question
