### ISSUE TITLE
SDK is chatty logging Service Bus polling via HTTP request auto-dependencies

### ISSUE THREAD

**Issue by jeffwilcox** [Microsoft/ApplicationInsights-node.js#157] opened 2016-12-16 21:14 UTC
Hi,
I'm wondering if this is the intention of the new auto-dependency collection code or not, but the Azure Service Bus Node.js library uses REST for long polling; I'm processing hundreds of thousands of service bus messages, including trying to see if messages are available, and now the general App Insights views are useless to me since all I see are service bus dependency events.

![servicebus-dependency](https://cloud.githubusercontent.com/assets/427913/21278701/8170e9be-c391-11e6-9d2a-19af318f08e7.PNG)

Thoughts on what the right approach might be? You can see the uptick in the picture when I turned on the new message bus processing code.

I'm happy to ignore the dependency view, but it feels like maybe that is not right... or do I need to configure in my app insights options that I have no interest in the service bus domains logging all of its goo?

**Comment by jeffwilcox** [comment] 2016-12-17 21:13
+ another example, now with 30-day time window 
<img width="568" alt="screen shot 2016-12-17 at 1 12 47 pm" src="https://cloud.githubusercontent.com/assets/427913/21289795/9cfefe2c-c45a-11e6-8e54-f5cb0c9fa1a7.png">

**Comment by SergeyKanzhelev** [comment] 2016-12-21 00:39
This is definitely not a good experience out of the box, we will review it.

As a workaround for now you can create a telemetry processor that will filter out all dependency calls made to this domain: https://github.com/Microsoft/ApplicationInsights-node.js/blob/33a7e7406db020fb4568d303fc2ca08307257f05/README.md#telemetry-processor

**Comment by kamilszostak** [comment] 2017-01-05 02:02
#156 allows adding a Service Bus URL to a list of excluded domains for dependency calls auto-collection. 

Do you think Azure Service Bus should be added to the [excluded list](https://github.com/Microsoft/ApplicationInsights-node.js/blob/66dc7cc1a3626c33f1c99fdabe628a75b5d2f8e1/Library/Config.ts#L35) by default, similar to Azure Storage?

**Comment by jeffwilcox** [comment] 2017-01-05 07:30
Thanks - thinking about this more, while I clearly would want to exclude it, I do not think all users would - and the behavior of app insights dependency work does not impact service bus or break it, so it's a different situation. Many users might want that data...

**Comment by kamilszostak** [comment] 2017-01-05 16:55
Sorry, I misunderstood the issue. The #156 will only disable the correlation headers, which were breaking Azure storage communication. 

This won't help in your case. I think the only solution is to use a [telemetry processor](https://github.com/Microsoft/ApplicationInsights-node.js/blob/33a7e7406db020fb4568d303fc2ca08307257f05/README.md#telemetry-processor) as @SergeyKanzhelev suggested.

**Comment by OsvaldoRosado** [comment] 2017-05-05 22:24
I think a telemetry processor was the correct solution here. These were all valid dependency calls, any of which could have failed or taken a strange duration (which is valid telemetry). We can try to be smart about detecting potential long polls or edge cases of well-known dependencies, but that seems like it has the potential to eliminate valid data that autocollection was intended to collect.

If this isn't good OOB, perhaps this should be fixed at the UI level? @SergeyKanzhelev  @KamilSzostak thoughts? Okay to close?

**Comment by jeffwilcox** [comment] 2017-07-14 05:34
Recently was reviewing our monthly bill and noticed that we have about $1,000/mo. currently of data overage coming from logging these Service Bus events as well as Redis dependencies.

The Redis dependencies are easy enough to configure away with the environment variables, but for Service Bus, I'm having a hard time... if I use a telemetry processor that just logs/outputs all data from the envelope, I am not seeing the outgoing HTTP requests being sent to the telemetry processor at all. Does this sound like something you would expect, or a bug?

As a result, I'm having a hard time figuring out how to skip logging these outgoing HTTP requests to Service Bus...

Appreciate any insights!

**Comment by OsvaldoRosado** [comment] 2017-07-14 05:44
Every telemetry item should be routed through all registered telemetry processors before transmission (unless any telemetry processors in the chain reject the item of course), If you are seeing any telemetry that the SDK is able to send without calling your telemetry processor, that is definitely a bug.

This logic is handled at the track method (https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/Library/Client.ts#L296). I don't see anything obvious that would let any items make it past the telemetry processor stage and still make it to transmission (the call to `channel.send`).

Could you share your logging telemetry processor?

**Comment by jeffwilcox** [comment] 2017-07-17 21:25
Thanks for your response. I haven't been able to look into this but will get on it soon. Appreciate you taking the time!

**Comment by AlexBulankou** [comment] 2017-08-18 20:35
Closing for now. @jeffwilcox, please reactivate with the code for telemetry processor, if you are still seeing the issue.

**Closed by AlexBulankou** 2017-08-18 20:35 UTC
Labels: enhancement, question
