### ISSUE TITLE
Allow to provide metric namespace

### ISSUE THREAD

**Issue by henryju** [microsoft/ApplicationInsights-node.js#609] opened 2020-04-02 15:14 UTC
Hi,

Looking at the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview?toc=%2Fazure%2Fazure-monitor%2Ftoc.json#namespace) and Application Insights dashboard, it seems metrics could be grouped by namespace.

Except if I missed something, this SDK doesn't allow to provide a namespace, and all metrics ends up in the `azure.applicationinsights` namespace.

![image](https://user-images.githubusercontent.com/281596/78265888-56d04f00-7505-11ea-97ef-dc2c66dc2a3e.png)

**Comment by tomi** [comment] 2020-04-29 13:19
Related to this. I have multiple node apps that all report to the same application insights instance in Azure. I'm using the cloud role to distinguish the apps and this works fine to separate the metrics for differents apps.

I'm also using the `applicationinsights-native-metrics` npm package to get native metrics, but these all end up in the same `azure.applicationinsights` namespace. I didn't find a way to filter them based on the cloud role in Azure, rendering them basically useless, as the metrics from separate apps are merged together. So it would be nice if one could provide a namespace to separate these native metrics into separate namespaces, or if the cloud role was somehow applied to these metrics as well.

**Comment by asos-craigmorten** [comment] 2020-05-03 10:48
Agree, this would be awesome.

R.E. Splitting by Cloud Role, @tomi does the option not show up using the `Add Filter` / `Apply Splitting` options? (P.S. haven't used `applicationinsights-native-metrics` so maybe that plugin isn't apply the context tags to it's metrics if not!).

R.E. Namespacing, looks like the .NET SDK handled this a couple of years ago (REF: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/759). This resulted in an update to the official bond schema for the Azure Monitor to add a `ns` namespace field which can be used by consuming SDKs.

Hence a PR into this codebase adding the same field to the bond schema, generate a new [DataPoint.ts](https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Declarations/Contracts/Generated/DataPoint.ts) class, update data point creation (REF: https://github.com/microsoft/ApplicationInsights-node.js/blob/develop/Library/EnvelopeFactory.ts#L208) to add `ns`, e.g.

```ts
    private static createMetricData(telemetry: Contracts.MetricTelemetry): Contracts.Data<Contracts.MetricData> {
        var metrics = new Contracts.MetricData(); // todo: enable client-batching of these
        metrics.metrics = [];

        var metric = new Contracts.DataPoint();
        metric.count = !isNaN(telemetry.count) ? telemetry.count : 1;
        metric.kind = Contracts.DataPointType.Aggregation;
        metric.max = !isNaN(telemetry.max) ? telemetry.max : telemetry.value;
        metric.min = !isNaN(telemetry.min) ? telemetry.min : telemetry.value;
        metric.name = telemetry.name;
        metric.ns = telemetry.namespace; // Something like this here
        metric.stdDev = !isNaN(telemetry.stdDev) ? telemetry.stdDev : 0;
        metric.value = telemetry.value;

        ...
```

And then consumers can call `track*()` methods with a custom`namespace`/`ns`/`metricNamespace` (name TBD) property if desired? Decisions r.e. whether there is a "default" namespace / how a consumer can set a global namespace would be need to be decided - think autocollection when have multiple Telemetry Clients.

References:
- Endpoint protocol: https://github.com/microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/ENDPOINT-PROTOCOL.md
- Endpoint Schemas: https://github.com/microsoft/ApplicationInsights-Home/tree/master/EndpointSpecs/Schemas/Bond
- DataPoint Schema: https://github.com/microsoft/ApplicationInsights-Home/blob/master/EndpointSpecs/Schemas/Bond/DataPoint.bond#L10
- Azure Monitor Track Endpoint: https://docs.microsoft.com/en-us/azure/azure-monitor/faq#can-i-send-telemetry-to-the-application-insights-portal
- DotNet issue: https://github.com/Microsoft/ApplicationInsights-dotnet/issues/759
- DotNet PR to add namespace: https://github.com/microsoft/ApplicationInsights-dotnet/commit/f7536327fb67de7652d7c4025cd318b9c8ae7016

**Comment by tomi** [comment] 2020-05-04 15:24
@asos-craigmorten yes, that seems to work! It seems I need to select `Log-based metrics` as the `Metric namespace` and then I can filter and split the data. If I choose the custom `azure.applicationinsights` namespace filtering and splitting is not available. So thank you, that solves my issue!

**Comment by jrauschenbusch** [comment] 2020-09-14 14:13
@asos-craigmorten Would you submit a PR for your namespace extension feature?

@tomi I think the root cause for the missing splitting feature with native metrics could be [this](https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#custom-metrics-dimensions-and-pre-aggregation
) one:
> All metrics that you send using trackMetric or GetMetric and TrackValue API calls are automatically stored in both logs and metrics stores. However, while the log-based version of your custom metric always retains all dimensions, the pre-aggregated version of the metric is stored by default with no dimensions. You can turn on collection of dimensions of custom metrics on the usage and estimated cost tab by checking "Enable alerting on custom metric dimensions":

**Comment by jrauschenbusch** [comment] 2020-09-15 11:53
@markwolff are there any plans from Microsoft to implement the namespace support?

**Comment by leidegre** [comment] 2021-10-08 06:53
Is there a limitation in the ingestion endpoint that is preventing this feature or some other consideration that is preventing this from being implemented? It looks to me that it's just another field in the bond files and types that needs to get mapped? Are there other important things to take into consideration when you use namespaces?

**Closed** 2021-11-15 18:13 UTC
Labels: enhancement, investigate, team-triaged
